# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  spartan_config = debug_x64

else ifeq ($(config),dev_x64)
  spartan_config = dev_x64

else ifeq ($(config),release_x64)
  spartan_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := spartan

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

spartan:
ifneq (,$(spartan_config))
	@echo "==== Building spartan ($(spartan_config)) ===="
	@${MAKE} --no-print-directory -C . -f spartan.make config=$(spartan_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f spartan.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  dev_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   spartan"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"