# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
PCH = source/runtime/Core/pch.h
PCH_PLACEHOLDER = $(OBJDIR)/$(notdir $(PCH))
GCH = $(PCH_PLACEHOLDER).gch
INCLUDES += -Isource -Isource/runtime -Isource/runtime/Core -Isource/editor -Ithird_party/install/include -Ithird_party/install/include/physx -Ithird_party/install/include/compressonator -I/usr/include/freetype2 -I/usr/include/lua5.4 -Ithird_party/free_image -Ithird_party/openxr -Ithird_party/lua -Ithird_party/spirv_cross -Ithird_party/vulkan -Ithird_party/fidelityfx -Ithird_party/xess -Ithird_party/vulkan_memory_allocator
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LDDEPS +=
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = binaries
TARGET = $(TARGETDIR)/spartan_vulkan_debug
OBJDIR = binaries/obj/x64/debug
DEFINES += -DDEBUG -DAPI_GRAPHICS_VULKAN -DFFX_BACKEND_VK -DFFX_STATIC_LIBRARIES
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -mavx2 -mfma
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O0 -g -std=c++20 -mavx2 -mfma
LIBS += -Wl,--start-group -llua -lassimp -lfreeimage -lfreetype -lSDL3 -lCMP_Compressonator -lCMP_Core_SSE -lCMP_Core_AVX -lCMP_Core_AVX512 -lCMP_Framework -lz -lpugixml -ldxcompiler -lNRD -lShaderMakeBlob -ldl -lopenxr_loader -lspirv-cross-core -lspirv-cross-c -lspirv-cross-glsl -lspirv-cross-cpp -lspirv-cross-hlsl -lspirv-cross-reflect -lmeshoptimizer -lvulkan -lPhysX_static_64 -lPhysXCommon_static_64 -lPhysXFoundation_static_64 -lPhysXExtensions_static_64 -lPhysXPvdSDK_static_64 -lPhysXCooking_static_64 -lPhysXVehicle2_static_64 -lPhysXCharacterKinematic_static_64 -Wl,--end-group
ALL_LDFLAGS += $(LDFLAGS) -Lthird_party/libraries -Lthird_party/install/lib -L/usr/lib64 -m64 -Wl,-rpath,'$$ORIGIN/../third_party/install/lib' -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib64 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib

else ifeq ($(config),dev_x64)
TARGETDIR = binaries
TARGET = $(TARGETDIR)/spartan_vulkan_dev
OBJDIR = binaries/obj/x64/dev
DEFINES += -DDEBUG -DAPI_GRAPHICS_VULKAN -DFFX_BACKEND_VK -DFFX_STATIC_LIBRARIES
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O3 -g -mavx2 -mfma
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O3 -g -std=c++20 -mavx2 -mfma
LIBS += -Wl,--start-group -llua -lassimp -lfreeimage -lfreetype -lSDL3 -lCMP_Compressonator -lCMP_Core_SSE -lCMP_Core_AVX -lCMP_Core_AVX512 -lCMP_Framework -lz -lpugixml -ldxcompiler -lNRD -lShaderMakeBlob -ldl -lopenxr_loader -lspirv-cross-core -lspirv-cross-c -lspirv-cross-glsl -lspirv-cross-cpp -lspirv-cross-hlsl -lspirv-cross-reflect -lmeshoptimizer -lvulkan -lPhysX_static_64 -lPhysXCommon_static_64 -lPhysXFoundation_static_64 -lPhysXExtensions_static_64 -lPhysXPvdSDK_static_64 -lPhysXCooking_static_64 -lPhysXVehicle2_static_64 -lPhysXCharacterKinematic_static_64 -Wl,--end-group
ALL_LDFLAGS += $(LDFLAGS) -Lthird_party/libraries -Lthird_party/install/lib -L/usr/lib64 -m64 -Wl,-rpath,'$$ORIGIN/../third_party/install/lib' -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib64 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib

else ifeq ($(config),release_x64)
TARGETDIR = binaries
TARGET = $(TARGETDIR)/spartan_vulkan
OBJDIR = binaries/obj/x64/release
DEFINES += -DAPI_GRAPHICS_VULKAN -DFFX_BACKEND_VK -DFFX_STATIC_LIBRARIES
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -mavx2 -mfma
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -std=c++20 -mavx2 -mfma
LIBS += -Wl,--start-group -lFreeImageLib -lCompressonator_MT -llua -lassimp -lfreeimage -lfreetype -lSDL3 -lCMP_Compressonator -lCMP_Core_SSE -lCMP_Core_AVX -lCMP_Core_AVX512 -lCMP_Framework -lz -lpugixml -ldxcompiler -lNRD -lShaderMakeBlob -ldl -lopenxr_loader -lspirv-cross-core -lspirv-cross-c -lspirv-cross-glsl -lspirv-cross-cpp -lspirv-cross-hlsl -lspirv-cross-reflect -lmeshoptimizer -lvulkan -lPhysX_static_64 -lPhysXCommon_static_64 -lPhysXFoundation_static_64 -lPhysXExtensions_static_64 -lPhysXPvdSDK_static_64 -lPhysXCooking_static_64 -lPhysXVehicle2_static_64 -lPhysXCharacterKinematic_static_64 -Wl,--end-group
ALL_LDFLAGS += $(LDFLAGS) -Lthird_party/libraries -Lthird_party/install/lib -L/usr/lib64 -m64 -flto -s -Wl,-rpath,'$$ORIGIN/../third_party/install/lib' -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib64 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/lib

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/Allocator.o
GENERATED += $(OBJDIR)/Animation.o
GENERATED += $(OBJDIR)/Animator.o
GENERATED += $(OBJDIR)/AssetBrowser.o
GENERATED += $(OBJDIR)/AudioSource.o
GENERATED += $(OBJDIR)/BoundingBox.o
GENERATED += $(OBJDIR)/Breadcrumbs.o
GENERATED += $(OBJDIR)/ButtonColorPicker.o
GENERATED += $(OBJDIR)/Camera.o
GENERATED += $(OBJDIR)/Car.o
GENERATED += $(OBJDIR)/Color.o
GENERATED += $(OBJDIR)/CommandEntityDelete.o
GENERATED += $(OBJDIR)/CommandStack.o
GENERATED += $(OBJDIR)/CommandTransform.o
GENERATED += $(OBJDIR)/CommandTransformMulti.o
GENERATED += $(OBJDIR)/Component.o
GENERATED += $(OBJDIR)/Console.o
GENERATED += $(OBJDIR)/ConsoleCommands.o
GENERATED += $(OBJDIR)/Contributors.o
GENERATED += $(OBJDIR)/Definitions.o
GENERATED += $(OBJDIR)/Display.o
GENERATED += $(OBJDIR)/Editor.o
GENERATED += $(OBJDIR)/Engine.o
GENERATED += $(OBJDIR)/Entity.o
GENERATED += $(OBJDIR)/Event.o
GENERATED += $(OBJDIR)/FileDialog.o
GENERATED += $(OBJDIR)/FileSystem.o
GENERATED += $(OBJDIR)/Font.o
GENERATED += $(OBJDIR)/FontImporter.o
GENERATED += $(OBJDIR)/Frustum.o
GENERATED += $(OBJDIR)/Game.o
GENERATED += $(OBJDIR)/GeneralWindows.o
GENERATED += $(OBJDIR)/GeometryBuffer.o
GENERATED += $(OBJDIR)/GraphEditor.o
GENERATED += $(OBJDIR)/IResource.o
GENERATED += $(OBJDIR)/ImCurveEdit.o
GENERATED += $(OBJDIR)/ImGradient.o
GENERATED += $(OBJDIR)/ImGuizmo.o
GENERATED += $(OBJDIR)/ImSequencer.o
GENERATED += $(OBJDIR)/ImageImporter.o
GENERATED += $(OBJDIR)/Input.o
GENERATED += $(OBJDIR)/InputGamepad.o
GENERATED += $(OBJDIR)/InputKeyboard.o
GENERATED += $(OBJDIR)/InputMouse.o
GENERATED += $(OBJDIR)/InputSteeringWheel.o
GENERATED += $(OBJDIR)/Light.o
GENERATED += $(OBJDIR)/Log.o
GENERATED += $(OBJDIR)/Material.o
GENERATED += $(OBJDIR)/Matrix.o
GENERATED += $(OBJDIR)/MemoryOverrides.o
GENERATED += $(OBJDIR)/MenuBar.o
GENERATED += $(OBJDIR)/Mesh.o
GENERATED += $(OBJDIR)/ModelImporter.o
GENERATED += $(OBJDIR)/ParticleSystem.o
GENERATED += $(OBJDIR)/Physics.o
GENERATED += $(OBJDIR)/PhysicsWorld.o
GENERATED += $(OBJDIR)/Plane.o
GENERATED += $(OBJDIR)/Prefab.o
GENERATED += $(OBJDIR)/Profiler.o
GENERATED += $(OBJDIR)/Profiler1.o
GENERATED += $(OBJDIR)/ProgressDialog.o
GENERATED += $(OBJDIR)/ProgressTracker.o
GENERATED += $(OBJDIR)/Properties.o
GENERATED += $(OBJDIR)/Quaternion.o
GENERATED += $(OBJDIR)/RHI_CommandList.o
GENERATED += $(OBJDIR)/RHI_DescriptorSet.o
GENERATED += $(OBJDIR)/RHI_DescriptorSetLayout.o
GENERATED += $(OBJDIR)/RHI_Device.o
GENERATED += $(OBJDIR)/RHI_Implementation.o
GENERATED += $(OBJDIR)/RHI_PhysicalDevice.o
GENERATED += $(OBJDIR)/RHI_PipelineState.o
GENERATED += $(OBJDIR)/RHI_Sampler.o
GENERATED += $(OBJDIR)/RHI_Shader.o
GENERATED += $(OBJDIR)/RHI_Texture.o
GENERATED += $(OBJDIR)/RHI_Viewport.o
GENERATED += $(OBJDIR)/Ray.o
GENERATED += $(OBJDIR)/Rectangle.o
GENERATED += $(OBJDIR)/RenderDoc.o
GENERATED += $(OBJDIR)/RenderOptions.o
GENERATED += $(OBJDIR)/Renderable.o
GENERATED += $(OBJDIR)/Renderer.o
GENERATED += $(OBJDIR)/Renderer_ConsoleVariables.o
GENERATED += $(OBJDIR)/Renderer_GpuSkinning.o
GENERATED += $(OBJDIR)/Renderer_Passes.o
GENERATED += $(OBJDIR)/Renderer_Primitives.o
GENERATED += $(OBJDIR)/Renderer_Resources.o
GENERATED += $(OBJDIR)/ResourceCache.o
GENERATED += $(OBJDIR)/ResourceViewer.o
GENERATED += $(OBJDIR)/Script.o
GENERATED += $(OBJDIR)/ScriptEditor.o
GENERATED += $(OBJDIR)/Settings.o
GENERATED += $(OBJDIR)/ShaderEditor.o
GENERATED += $(OBJDIR)/SkinningGeometryBuffer.o
GENERATED += $(OBJDIR)/SmokeTest.o
GENERATED += $(OBJDIR)/Sphere.o
GENERATED += $(OBJDIR)/Spline.o
GENERATED += $(OBJDIR)/SplineFollower.o
GENERATED += $(OBJDIR)/Style.o
GENERATED += $(OBJDIR)/Terrain.o
GENERATED += $(OBJDIR)/TextEditor.o
GENERATED += $(OBJDIR)/TextureViewer.o
GENERATED += $(OBJDIR)/ThreadPool.o
GENERATED += $(OBJDIR)/TimeBlock.o
GENERATED += $(OBJDIR)/Timer.o
GENERATED += $(OBJDIR)/Vector2.o
GENERATED += $(OBJDIR)/Vector3.o
GENERATED += $(OBJDIR)/Vector4.o
GENERATED += $(OBJDIR)/Viewport.o
GENERATED += $(OBJDIR)/Volume.o
GENERATED += $(OBJDIR)/Vulkan_AccelerationStructure.o
GENERATED += $(OBJDIR)/Vulkan_BlendState.o
GENERATED += $(OBJDIR)/Vulkan_Buffer.o
GENERATED += $(OBJDIR)/Vulkan_CommandList.o
GENERATED += $(OBJDIR)/Vulkan_DepthStencilState.o
GENERATED += $(OBJDIR)/Vulkan_DescriptorSet.o
GENERATED += $(OBJDIR)/Vulkan_DescriptorSetLayout.o
GENERATED += $(OBJDIR)/Vulkan_Device.o
GENERATED += $(OBJDIR)/Vulkan_InputLayout.o
GENERATED += $(OBJDIR)/Vulkan_Pipeline.o
GENERATED += $(OBJDIR)/Vulkan_Queue.o
GENERATED += $(OBJDIR)/Vulkan_RasterizerState.o
GENERATED += $(OBJDIR)/Vulkan_Sampler.o
GENERATED += $(OBJDIR)/Vulkan_Shader.o
GENERATED += $(OBJDIR)/Vulkan_SwapChain.o
GENERATED += $(OBJDIR)/Vulkan_SyncPrimitive.o
GENERATED += $(OBJDIR)/Vulkan_Texture.o
GENERATED += $(OBJDIR)/Vulkan_VendorTechnology.o
GENERATED += $(OBJDIR)/Widget.o
GENERATED += $(OBJDIR)/Window.o
GENERATED += $(OBJDIR)/World.o
GENERATED += $(OBJDIR)/WorldSelector.o
GENERATED += $(OBJDIR)/WorldViewer.o
GENERATED += $(OBJDIR)/Xr.o
GENERATED += $(OBJDIR)/imgui.o
GENERATED += $(OBJDIR)/imgui_demo.o
GENERATED += $(OBJDIR)/imgui_draw.o
GENERATED += $(OBJDIR)/imgui_freetype.o
GENERATED += $(OBJDIR)/imgui_impl_sdl3.o
GENERATED += $(OBJDIR)/imgui_stdlib.o
GENERATED += $(OBJDIR)/imgui_tables.o
GENERATED += $(OBJDIR)/imgui_widgets.o
GENERATED += $(OBJDIR)/main.o
GENERATED += $(OBJDIR)/main1.o
GENERATED += $(OBJDIR)/pch.o
OBJECTS += $(OBJDIR)/Allocator.o
OBJECTS += $(OBJDIR)/Animation.o
OBJECTS += $(OBJDIR)/Animator.o
OBJECTS += $(OBJDIR)/AssetBrowser.o
OBJECTS += $(OBJDIR)/AudioSource.o
OBJECTS += $(OBJDIR)/BoundingBox.o
OBJECTS += $(OBJDIR)/Breadcrumbs.o
OBJECTS += $(OBJDIR)/ButtonColorPicker.o
OBJECTS += $(OBJDIR)/Camera.o
OBJECTS += $(OBJDIR)/Car.o
OBJECTS += $(OBJDIR)/Color.o
OBJECTS += $(OBJDIR)/CommandEntityDelete.o
OBJECTS += $(OBJDIR)/CommandStack.o
OBJECTS += $(OBJDIR)/CommandTransform.o
OBJECTS += $(OBJDIR)/CommandTransformMulti.o
OBJECTS += $(OBJDIR)/Component.o
OBJECTS += $(OBJDIR)/Console.o
OBJECTS += $(OBJDIR)/ConsoleCommands.o
OBJECTS += $(OBJDIR)/Contributors.o
OBJECTS += $(OBJDIR)/Definitions.o
OBJECTS += $(OBJDIR)/Display.o
OBJECTS += $(OBJDIR)/Editor.o
OBJECTS += $(OBJDIR)/Engine.o
OBJECTS += $(OBJDIR)/Entity.o
OBJECTS += $(OBJDIR)/Event.o
OBJECTS += $(OBJDIR)/FileDialog.o
OBJECTS += $(OBJDIR)/FileSystem.o
OBJECTS += $(OBJDIR)/Font.o
OBJECTS += $(OBJDIR)/FontImporter.o
OBJECTS += $(OBJDIR)/Frustum.o
OBJECTS += $(OBJDIR)/Game.o
OBJECTS += $(OBJDIR)/GeneralWindows.o
OBJECTS += $(OBJDIR)/GeometryBuffer.o
OBJECTS += $(OBJDIR)/GraphEditor.o
OBJECTS += $(OBJDIR)/IResource.o
OBJECTS += $(OBJDIR)/ImCurveEdit.o
OBJECTS += $(OBJDIR)/ImGradient.o
OBJECTS += $(OBJDIR)/ImGuizmo.o
OBJECTS += $(OBJDIR)/ImSequencer.o
OBJECTS += $(OBJDIR)/ImageImporter.o
OBJECTS += $(OBJDIR)/Input.o
OBJECTS += $(OBJDIR)/InputGamepad.o
OBJECTS += $(OBJDIR)/InputKeyboard.o
OBJECTS += $(OBJDIR)/InputMouse.o
OBJECTS += $(OBJDIR)/InputSteeringWheel.o
OBJECTS += $(OBJDIR)/Light.o
OBJECTS += $(OBJDIR)/Log.o
OBJECTS += $(OBJDIR)/Material.o
OBJECTS += $(OBJDIR)/Matrix.o
OBJECTS += $(OBJDIR)/MemoryOverrides.o
OBJECTS += $(OBJDIR)/MenuBar.o
OBJECTS += $(OBJDIR)/Mesh.o
OBJECTS += $(OBJDIR)/ModelImporter.o
OBJECTS += $(OBJDIR)/ParticleSystem.o
OBJECTS += $(OBJDIR)/Physics.o
OBJECTS += $(OBJDIR)/PhysicsWorld.o
OBJECTS += $(OBJDIR)/Plane.o
OBJECTS += $(OBJDIR)/Prefab.o
OBJECTS += $(OBJDIR)/Profiler.o
OBJECTS += $(OBJDIR)/Profiler1.o
OBJECTS += $(OBJDIR)/ProgressDialog.o
OBJECTS += $(OBJDIR)/ProgressTracker.o
OBJECTS += $(OBJDIR)/Properties.o
OBJECTS += $(OBJDIR)/Quaternion.o
OBJECTS += $(OBJDIR)/RHI_CommandList.o
OBJECTS += $(OBJDIR)/RHI_DescriptorSet.o
OBJECTS += $(OBJDIR)/RHI_DescriptorSetLayout.o
OBJECTS += $(OBJDIR)/RHI_Device.o
OBJECTS += $(OBJDIR)/RHI_Implementation.o
OBJECTS += $(OBJDIR)/RHI_PhysicalDevice.o
OBJECTS += $(OBJDIR)/RHI_PipelineState.o
OBJECTS += $(OBJDIR)/RHI_Sampler.o
OBJECTS += $(OBJDIR)/RHI_Shader.o
OBJECTS += $(OBJDIR)/RHI_Texture.o
OBJECTS += $(OBJDIR)/RHI_Viewport.o
OBJECTS += $(OBJDIR)/Ray.o
OBJECTS += $(OBJDIR)/Rectangle.o
OBJECTS += $(OBJDIR)/RenderDoc.o
OBJECTS += $(OBJDIR)/RenderOptions.o
OBJECTS += $(OBJDIR)/Renderable.o
OBJECTS += $(OBJDIR)/Renderer.o
OBJECTS += $(OBJDIR)/Renderer_ConsoleVariables.o
OBJECTS += $(OBJDIR)/Renderer_GpuSkinning.o
OBJECTS += $(OBJDIR)/Renderer_Passes.o
OBJECTS += $(OBJDIR)/Renderer_Primitives.o
OBJECTS += $(OBJDIR)/Renderer_Resources.o
OBJECTS += $(OBJDIR)/ResourceCache.o
OBJECTS += $(OBJDIR)/ResourceViewer.o
OBJECTS += $(OBJDIR)/Script.o
OBJECTS += $(OBJDIR)/ScriptEditor.o
OBJECTS += $(OBJDIR)/Settings.o
OBJECTS += $(OBJDIR)/ShaderEditor.o
OBJECTS += $(OBJDIR)/SkinningGeometryBuffer.o
OBJECTS += $(OBJDIR)/SmokeTest.o
OBJECTS += $(OBJDIR)/Sphere.o
OBJECTS += $(OBJDIR)/Spline.o
OBJECTS += $(OBJDIR)/SplineFollower.o
OBJECTS += $(OBJDIR)/Style.o
OBJECTS += $(OBJDIR)/Terrain.o
OBJECTS += $(OBJDIR)/TextEditor.o
OBJECTS += $(OBJDIR)/TextureViewer.o
OBJECTS += $(OBJDIR)/ThreadPool.o
OBJECTS += $(OBJDIR)/TimeBlock.o
OBJECTS += $(OBJDIR)/Timer.o
OBJECTS += $(OBJDIR)/Vector2.o
OBJECTS += $(OBJDIR)/Vector3.o
OBJECTS += $(OBJDIR)/Vector4.o
OBJECTS += $(OBJDIR)/Viewport.o
OBJECTS += $(OBJDIR)/Volume.o
OBJECTS += $(OBJDIR)/Vulkan_AccelerationStructure.o
OBJECTS += $(OBJDIR)/Vulkan_BlendState.o
OBJECTS += $(OBJDIR)/Vulkan_Buffer.o
OBJECTS += $(OBJDIR)/Vulkan_CommandList.o
OBJECTS += $(OBJDIR)/Vulkan_DepthStencilState.o
OBJECTS += $(OBJDIR)/Vulkan_DescriptorSet.o
OBJECTS += $(OBJDIR)/Vulkan_DescriptorSetLayout.o
OBJECTS += $(OBJDIR)/Vulkan_Device.o
OBJECTS += $(OBJDIR)/Vulkan_InputLayout.o
OBJECTS += $(OBJDIR)/Vulkan_Pipeline.o
OBJECTS += $(OBJDIR)/Vulkan_Queue.o
OBJECTS += $(OBJDIR)/Vulkan_RasterizerState.o
OBJECTS += $(OBJDIR)/Vulkan_Sampler.o
OBJECTS += $(OBJDIR)/Vulkan_Shader.o
OBJECTS += $(OBJDIR)/Vulkan_SwapChain.o
OBJECTS += $(OBJDIR)/Vulkan_SyncPrimitive.o
OBJECTS += $(OBJDIR)/Vulkan_Texture.o
OBJECTS += $(OBJDIR)/Vulkan_VendorTechnology.o
OBJECTS += $(OBJDIR)/Widget.o
OBJECTS += $(OBJDIR)/Window.o
OBJECTS += $(OBJDIR)/World.o
OBJECTS += $(OBJDIR)/WorldSelector.o
OBJECTS += $(OBJDIR)/WorldViewer.o
OBJECTS += $(OBJDIR)/Xr.o
OBJECTS += $(OBJDIR)/imgui.o
OBJECTS += $(OBJDIR)/imgui_demo.o
OBJECTS += $(OBJDIR)/imgui_draw.o
OBJECTS += $(OBJDIR)/imgui_freetype.o
OBJECTS += $(OBJDIR)/imgui_impl_sdl3.o
OBJECTS += $(OBJDIR)/imgui_stdlib.o
OBJECTS += $(OBJDIR)/imgui_tables.o
OBJECTS += $(OBJDIR)/imgui_widgets.o
OBJECTS += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/main1.o
OBJECTS += $(OBJDIR)/pch.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking spartan
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning spartan
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/Editor.o: source/editor/Editor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GeneralWindows.o: source/editor/GeneralWindows.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_impl_sdl3.o: source/editor/ImGui/Implementation/imgui_impl_sdl3.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GraphEditor.o: source/editor/ImGui/Source/ImGuizmo/GraphEditor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImCurveEdit.o: source/editor/ImGui/Source/ImGuizmo/ImCurveEdit.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGradient.o: source/editor/ImGui/Source/ImGuizmo/ImGradient.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImGuizmo.o: source/editor/ImGui/Source/ImGuizmo/ImGuizmo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImSequencer.o: source/editor/ImGui/Source/ImGuizmo/ImSequencer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui.o: source/editor/ImGui/Source/imgui.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_demo.o: source/editor/ImGui/Source/imgui_demo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_draw.o: source/editor/ImGui/Source/imgui_draw.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_freetype.o: source/editor/ImGui/Source/imgui_freetype.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_stdlib.o: source/editor/ImGui/Source/imgui_stdlib.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_tables.o: source/editor/ImGui/Source/imgui_tables.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/imgui_widgets.o: source/editor/ImGui/Source/imgui_widgets.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TextEditor.o: source/editor/ImGui/TextEditor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AssetBrowser.o: source/editor/Widgets/AssetBrowser.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ButtonColorPicker.o: source/editor/Widgets/ButtonColorPicker.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Console.o: source/editor/Widgets/Console.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FileDialog.o: source/editor/Widgets/FileDialog.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MenuBar.o: source/editor/Widgets/MenuBar.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Profiler.o: source/editor/Widgets/Profiler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ProgressDialog.o: source/editor/Widgets/ProgressDialog.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Properties.o: source/editor/Widgets/Properties.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RenderOptions.o: source/editor/Widgets/RenderOptions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ResourceViewer.o: source/editor/Widgets/ResourceViewer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ScriptEditor.o: source/editor/Widgets/ScriptEditor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ShaderEditor.o: source/editor/Widgets/ShaderEditor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Style.o: source/editor/Widgets/Style.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TextureViewer.o: source/editor/Widgets/TextureViewer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Viewport.o: source/editor/Widgets/Viewport.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Widget.o: source/editor/Widgets/Widget.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WorldViewer.o: source/editor/Widgets/WorldViewer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Contributors.o: source/editor/Windows/Contributors.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WorldSelector.o: source/editor/Windows/WorldSelector.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main.o: source/editor/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Car.o: source/runtime/Car/Car.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CommandEntityDelete.o: source/runtime/Commands/CommandEntityDelete.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CommandStack.o: source/runtime/Commands/CommandStack.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CommandTransform.o: source/runtime/Commands/CommandTransform.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CommandTransformMulti.o: source/runtime/Commands/CommandTransformMulti.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConsoleCommands.o: source/runtime/Commands/Console/ConsoleCommands.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Breadcrumbs.o: source/runtime/Core/Breadcrumbs.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Definitions.o: source/runtime/Core/Definitions.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Engine.o: source/runtime/Core/Engine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Event.o: source/runtime/Core/Event.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ProgressTracker.o: source/runtime/Core/ProgressTracker.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Settings.o: source/runtime/Core/Settings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ThreadPool.o: source/runtime/Core/ThreadPool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Timer.o: source/runtime/Core/Timer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Window.o: source/runtime/Core/Window.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pch.o: source/runtime/Core/pch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Display.o: source/runtime/Display/Display.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FileSystem.o: source/runtime/FileSystem/FileSystem.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Font.o: source/runtime/Font/Font.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Game.o: source/runtime/Game/Game.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Mesh.o: source/runtime/Geometry/Mesh.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Input.o: source/runtime/Input/Input.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputGamepad.o: source/runtime/Input/InputGamepad.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputKeyboard.o: source/runtime/Input/InputKeyboard.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputMouse.o: source/runtime/Input/InputMouse.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/InputSteeringWheel.o: source/runtime/Input/InputSteeringWheel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Log.o: source/runtime/Logging/Log.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BoundingBox.o: source/runtime/Math/BoundingBox.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Frustum.o: source/runtime/Math/Frustum.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Matrix.o: source/runtime/Math/Matrix.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Plane.o: source/runtime/Math/Plane.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Quaternion.o: source/runtime/Math/Quaternion.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Ray.o: source/runtime/Math/Ray.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Rectangle.o: source/runtime/Math/Rectangle.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Sphere.o: source/runtime/Math/Sphere.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vector2.o: source/runtime/Math/Vector2.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vector3.o: source/runtime/Math/Vector3.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vector4.o: source/runtime/Math/Vector4.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Allocator.o: source/runtime/Memory/Allocator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MemoryOverrides.o: source/runtime/Memory/MemoryOverrides.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsWorld.o: source/runtime/Physics/PhysicsWorld.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Profiler1.o: source/runtime/Profiling/Profiler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RenderDoc.o: source/runtime/Profiling/RenderDoc.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TimeBlock.o: source/runtime/Profiling/TimeBlock.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_CommandList.o: source/runtime/RHI/RHI_CommandList.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_DescriptorSet.o: source/runtime/RHI/RHI_DescriptorSet.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_DescriptorSetLayout.o: source/runtime/RHI/RHI_DescriptorSetLayout.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_Device.o: source/runtime/RHI/RHI_Device.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_Implementation.o: source/runtime/RHI/RHI_Implementation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_PhysicalDevice.o: source/runtime/RHI/RHI_PhysicalDevice.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_PipelineState.o: source/runtime/RHI/RHI_PipelineState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_Sampler.o: source/runtime/RHI/RHI_Sampler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_Shader.o: source/runtime/RHI/RHI_Shader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_Texture.o: source/runtime/RHI/RHI_Texture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RHI_Viewport.o: source/runtime/RHI/RHI_Viewport.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_AccelerationStructure.o: source/runtime/RHI/Vulkan/Vulkan_AccelerationStructure.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_BlendState.o: source/runtime/RHI/Vulkan/Vulkan_BlendState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_Buffer.o: source/runtime/RHI/Vulkan/Vulkan_Buffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_CommandList.o: source/runtime/RHI/Vulkan/Vulkan_CommandList.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_DepthStencilState.o: source/runtime/RHI/Vulkan/Vulkan_DepthStencilState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_DescriptorSet.o: source/runtime/RHI/Vulkan/Vulkan_DescriptorSet.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_DescriptorSetLayout.o: source/runtime/RHI/Vulkan/Vulkan_DescriptorSetLayout.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_Device.o: source/runtime/RHI/Vulkan/Vulkan_Device.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_InputLayout.o: source/runtime/RHI/Vulkan/Vulkan_InputLayout.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_Pipeline.o: source/runtime/RHI/Vulkan/Vulkan_Pipeline.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_Queue.o: source/runtime/RHI/Vulkan/Vulkan_Queue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_RasterizerState.o: source/runtime/RHI/Vulkan/Vulkan_RasterizerState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_Sampler.o: source/runtime/RHI/Vulkan/Vulkan_Sampler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_Shader.o: source/runtime/RHI/Vulkan/Vulkan_Shader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_SwapChain.o: source/runtime/RHI/Vulkan/Vulkan_SwapChain.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_SyncPrimitive.o: source/runtime/RHI/Vulkan/Vulkan_SyncPrimitive.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_Texture.o: source/runtime/RHI/Vulkan/Vulkan_Texture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vulkan_VendorTechnology.o: source/runtime/RHI/Vulkan/Vulkan_VendorTechnology.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Animation.o: source/runtime/Rendering/Animation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Color.o: source/runtime/Rendering/Color.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GeometryBuffer.o: source/runtime/Rendering/GeometryBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Material.o: source/runtime/Rendering/Material.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderer.o: source/runtime/Rendering/Renderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderer_ConsoleVariables.o: source/runtime/Rendering/Renderer_ConsoleVariables.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderer_GpuSkinning.o: source/runtime/Rendering/Renderer_GpuSkinning.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderer_Passes.o: source/runtime/Rendering/Renderer_Passes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderer_Primitives.o: source/runtime/Rendering/Renderer_Primitives.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderer_Resources.o: source/runtime/Rendering/Renderer_Resources.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkinningGeometryBuffer.o: source/runtime/Rendering/SkinningGeometryBuffer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IResource.o: source/runtime/Resource/IResource.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FontImporter.o: source/runtime/Resource/Import/FontImporter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ImageImporter.o: source/runtime/Resource/Import/ImageImporter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ModelImporter.o: source/runtime/Resource/Import/ModelImporter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ResourceCache.o: source/runtime/Resource/ResourceCache.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SmokeTest.o: source/runtime/Testing/SmokeTest.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Animator.o: source/runtime/World/Components/Animator.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/AudioSource.o: source/runtime/World/Components/AudioSource.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Camera.o: source/runtime/World/Components/Camera.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Component.o: source/runtime/World/Components/Component.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Light.o: source/runtime/World/Components/Light.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ParticleSystem.o: source/runtime/World/Components/ParticleSystem.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Physics.o: source/runtime/World/Components/Physics.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Renderable.o: source/runtime/World/Components/Renderable.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Script.o: source/runtime/World/Components/Script.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Spline.o: source/runtime/World/Components/Spline.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SplineFollower.o: source/runtime/World/Components/SplineFollower.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Terrain.o: source/runtime/World/Components/Terrain.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Volume.o: source/runtime/World/Components/Volume.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Entity.o: source/runtime/World/Entity.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Prefab.o: source/runtime/World/Prefab.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/World.o: source/runtime/World/World.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Xr.o: source/runtime/XR/Xr.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/main1.o: source/runtime/main.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) -include $(PCH_PLACEHOLDER) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif